name: Incorporate Benchmark Data
#     ^^^^^^^^^^^^^^^^^^^^^^^^^^
# This string is matched in `latest-artifact-for-branch.py`:

on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - develop
      - master
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    # Don't run on pull requests into the develop branch (b/c takes too long)
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build-core:
    runs-on: ubuntu-latest
    container: mjambon/r2c-ocaml:alpine
    steps:
      - name: Pre-checkout fixes
        run:  |
          sudo chmod -R 777 /github
          github_cache_dir="/__w"
          sudo mkdir -p "$github_cache_dir"
          sudo chmod -R 777 "$github_cache_dir"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Post-checkout fixes
        run: ./.github/post-checkout
      - name: Build semgrep-core
        run: ./install-scripts/install-alpine-semgrep-core
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: semgrep-core
          path: artifacts/semgrep-core
  benchmark-persist:
    runs-on: ubuntu-latest
    needs: [build-core]
    strategy:
      matrix:
        python: [3.7]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: semgrep-core
          path: semgrep-core-dir
      - name: Install artifact
        run: |
          sudo cp semgrep-core-dir/semgrep-core /usr/bin/semgrep-core
          sudo chmod +x /usr/bin/semgrep-core
      - name: Retrieve the latest performance run
        run: ./install-scripts/latest-artifact-for-branch.py
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BENCHMARK: "y"
          BRANCH: "develop"
          OUT_DIR: "semgrep/benchmarks"
      - name: Install bootstrapping packages for Python
        run: |
          export PATH=/github/home/.local/bin:$PATH
          pip3 install pipenv==2018.11.26 wheel==0.34.2
      - name: Install semgrep
        run: |
          cd semgrep
          export PATH=/github/home/.local/bin:$PATH
          pipenv install --dev
      - name: check semgrep
        run: |
          cd semgrep
          export PATH=/github/home/.local/bin:$PATH
          pipenv run semgrep --version
      - uses: actions/cache@v2
        with:
          path: ~/.cache/semgrep-cache
          key: semgrep-repo-cache-bench
      - name: run benchmarks
        run: |
          cd semgrep
          mkdir -p ~/.cache/semgrep-cache
          # TODO: figure out what checks we want to run on PRs
          eval $(opam  env --root /home/opam/.opam --set-root)
          export PATH=/github/home/.local/bin:$PATH
          pipenv run pytest -k test_ci_perf tests/ --benchmark-min-rounds 1 --benchmark-only --benchmark-autosave --benchmark-storage benchmarks
        env:
          GITHUB_REPO_CACHE: ~/.cache/semgrep-cache
      - name: Compare to previous benchmark result
        run: |
          cd semgrep
          eval $(opam  env --root /home/opam/.opam --set-root)
          export PATH=/github/home/.local/bin:$PATH
          pipenv run py.test-benchmark compare benchmarks/Linux-*/* --group-by name --sort name
        # compare to previous runs, even if we had a timeout or a test failure
        if: ${{ always() }}
      - name: Upload benchmark results
        uses: actions/upload-artifact@v1
        with:
          name: benchmarks
          path: semgrep/benchmarks
