name: homebrew-test

on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master, develop]

jobs:
  test-homebrew-external:
    runs-on: macos-latest
    steps:
      - name: Homebrew install
        run: brew install returntocorp/semgrep/semgrep
      - name: Homebrew test
        run: brew test returntocorp/semgrep/semgrep
