# This workflow builds and tests the semgrep-core binary for macOS arm64
# and generates the arm64-wheel for pypi.

# coupling: if you modify this file, modify also build-test-osx-x86.yaml
# This file is mostly a copy-paste of build-test-osx-x86.yaml
name: build-test-osx-arm64

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: "Use Opam Cache - uncheck the box to disable use of the opam cache, meaning a long-running but completely from-scratch build."
        required: true
        type: boolean
        default: true
  workflow_call:
    inputs:
      use-cache:
        description: "Use Opam Cache - uncheck the box to disable use of the opam cache, meaning a long-running but completely from-scratch build."
        required: false
        type: boolean
        default: true

jobs:
  evaluate-tags:
    name: Evalute Architecture Build Tags
    runs-on: ubuntu-22.04
    outputs:
      runs-on: ${{steps.runs-on.outputs.runs-on}}
    steps:
      - name: Generate `runs-on` tag list
        id: runs-on
        run: |
          echo "runs-on=['self-hosted','macOS','ARM64','ghcr.io/cirruslabs/macos-monterey-xcode:latest']" >> $GITHUB_OUTPUT
  build-core-m1:
    name: Build the OSX M1 binaries
    needs: [evaluate-tags]
    runs-on: ${{ fromJson(needs.evaluate-tags.outputs.runs-on) }}
    env:
      OPAM_SWITCH_NAME: "4.14.0"
    steps:
      - name: Setup runner directory
        run: |
          sudo mkdir /Users/runner
          sudo chown admin:staff /Users/runner
          sudo chmod 750 /Users/runner
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/checkout@v3
        with:
          submodules: true
      # Note that this action handles both cache read and cache write.
      # See https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows for more information on GHA caching.
      - name: Cache Opam
        id: cache-opam
        uses: actions/cache@v3
        if: ${{ inputs.use-cache || github.event_name == 'pull_request' }}
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
        with:
          path: ~/.opam
          key: "${{ runner.os }}-${{ runner.arch }}-${{ env.OPAM_SWITCH_NAME }}-opam-deps"
      - name: Install dependencies
        run: |
          ./scripts/osx-setup-for-release.sh "${{ env.OPAM_SWITCH_NAME }}"
      - name: Compile semgrep
        run: |
          opam exec -- make core
          mkdir -p artifacts
          cp ./bin/semgrep-core artifacts
          zip -r artifacts.zip artifacts
      - uses: actions/upload-artifact@v3
        with:
          path: artifacts.zip
          name: semgrep-osx-arm64-${{ github.sha }}

  build-wheels-osx-arm64:
    runs-on:
      [
        "self-hosted",
        "macOS",
        "ARM64",
        "ghcr.io/cirruslabs/macos-monterey-base:latest",
      ]
    needs: [build-core-osx-arm64]
    steps:
      - name: Setup runner directory
        run: |
          sudo mkdir /Users/runner
          sudo chmod 750 /Users/runner
          sudo chown -R admin:staff /Users/runner
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/download-artifact@v3
        with:
          name: semgrep-osx-arm64-${{ github.sha }}
      - name: Build Wheels
        run: |
          unzip artifacts.zip
          cp artifacts/semgrep-core cli/src/semgrep/bin
          ./scripts/build-wheels.sh --plat-name macosx_11_0_arm64
      - uses: actions/upload-artifact@v3
        with:
          path: cli/dist.zip
          name: osx-arm64-wheel

  test-wheels-osx-arm64:
    runs-on:
      [
        "self-hosted",
        "macOS",
        "ARM64",
        "ghcr.io/cirruslabs/macos-monterey-base:latest",
      ]
    needs: [build-wheels-osx-arm64]
    steps:
      - name: Setup runner directory
        run: |
          sudo mkdir /Users/runner
          sudo chmod 750 /Users/runner
          sudo chown -R admin:staff /Users/runner
      - uses: actions/download-artifact@v1
        with:
          name: osx-arm64-wheel
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: unzip ./osx-arm64-wheel/dist.zip
      - name: install package
        run: pip3 install dist/*.whl
      - run: semgrep --version
      - name: e2e semgrep-core test
        run: echo '1 == 1' | semgrep -l python -e '$X == $X' -
      - name: test dynamically linked libraries are in /usr/lib/
        shell: bash {0}
        run: |
          otool -L $(semgrep --dump-engine-path) > otool.txt
          if [ $? -ne 0 ]; then
            echo "Failed to list dynamically linked libraries.";
            cat otool.txt;
            exit 1;
          fi
          NON_USR_LIB_DYNAMIC_LIBRARIES=$(cat otool.txt | tail -n +2 | grep -v "^\s*/usr/lib/")
          if [ $? -eq 0 ]; then
            echo "Error: semgrep-core has been dynamically linked against libraries outside /usr/lib:"
            echo $NON_USR_LIB_DYNAMIC_LIBRARIES
            exit 1;
          fi;
