name: Push Semgrep Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t semgrep-dev .
      - name: Check the Docker image
        run: ./scripts/validate-docker-build.sh semgrep-dev
      - name: Push Develop Image if on develop branch
        if: ${{ github.event_name == 'push'}}
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: returntocorp/semgrep
          tags: develop
      - name: Push Commit Hash if PR
        if: ${{ github.event_name == 'pull_request' }} && ${{ secrets.DOCKER_USERNAME }}
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: returntocorp/semgrep
          tags: ${{ github.event.pull_request.head.sha }}
      - name: update dev.semgrep.dev
        run: curl --fail -X POST https://dev.semgrep.dev/api/admin/update-docker
      - name: update staging.semgrep.dev
        run: curl --fail -X POST https://staging.semgrep.dev/api/admin/update-docker
      - name: update semgrep.dev
        run: curl --fail -X POST https://semgrep.dev/api/admin/update-docker
