name: release-ubuntu-16-04

on:
  push:
    branches: [master, develop, experimental]
  pull_request:
    # TODO delete
    branches: [experimental]

jobs:
  release-ubuntu-16-04:
    runs-on: ubuntu-latest
    container: ocaml/opam2:ubuntu-16.04
    steps:
      - name: Setup Environment
        run: ./release-scripts/ubuntu-setup.sh
      - name: Adjust permissions
        run: sudo chmod -R 777 . /github
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Ubuntu build script
        run: ./release-scripts/ubuntu-release.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: sgrep-ubuntu-16.04-${{ github.sha }}
          path: sgrep-ubuntu-16.04.tar.gz
