# Workflow to manually revert the semgrep 'latest' docker image
# to a previous version.

name: Revert Semgrep Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker Tag to point 'latest' to, example: 0.100.0"
        required: true

jobs:
  rollback-docker-image:
    name: Rollback returntocorp/semgrep Docker Image
    runs-on: ubuntu-22.04
    env:
      DOCKER_IMAGE_REPO: returntocorp/semgrep
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: pull
        name: Pull Image to Retag as Latest
        run: |
          docker pull ${{ env.DOCKER_IMAGE_REPO }}:${{ inputs.docker_tag }}
      - id: retag
        name: Re-Tag Docker Image
        run: |
          docker tag ${{ env.DOCKER_IMAGE_REPO }}:${{ inputs.docker_tag }} ${{ env.DOCKER_IMAGE_REPO }}:latest
      - id: push
        name: Push New Latest Tag
        run: |
          docker push ${{ env.DOCKER_IMAGE_REPO }}:latest
