# Validate the artifacts produced by release.yml.
# This can be manually triggered or automatically by start-release.yml
# once release.yml has finished.

name: validate-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version to validate"
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  sanity_check_release:
    name: Sanity check the release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "v${{ inputs.version }}"
      - name: Validate the release
        run: ./scripts/validate-release.py ${{ inputs.version }}

  verify_docker_release:
    name: Verify the docker release works
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "v${{ inputs.version }}"
      - name: Validate docker release
        run: ./scripts/validate-docker-release.sh ${{ inputs.version }}

  verify_ubuntu_release:
    name: Verify the ubuntu release works
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "v${{ inputs.version }}"
      # Although this action can do the checkout step for us, it is more explicit and maintainable to pass context in this manner.
      - name: build tester image
        uses: docker/build-push-action@v4
        with:
          push: false
          context: "scripts"
          file: scripts/Dockerfile.16.04
          build-args: version=${{ inputs.version }}
